# Environment file for track-insights

name: track-insights

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11.5
  - pip
  - pip:
    - selenium
    - selenium-requests
  - beautifulsoup4
  - requests
  - jsonschema
  - tqdm
  - pyaml
  - sqlalchemy>=2.0
  - pymysql
  - pandas
  - numpy
  - types-PyYAML
  - tldextract
  - chardet
