# Environment file for track-insights

name: track-insights

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.10
  - pip
  - pip:
      - selenium
      - beautifulsoup4
      - jsonschema
      - pyaml
      - sqlalchemy>=2.0
      - pymysql
      - selenium-requests
      - pandas
      - numpy
